#!/bin/bash

# Converts subreads.bam file generated by the pacBio Sequel to a fastq file containing CCS, as described in Jamy et al, 2019

# usage: subreads2ccs.sh <subreads>

# Requires that the following softwares are installed:
## ccs (https://github.com/PacificBiosciences/unanimity)

# parameters
sample=$1

THREADS=16
MINLENGTH=1000
MAXLENGTH=7000
MINPASSES=2
MINSNR="0.75"
MINPREDICTEDACCURACY="0.99"
MINREADSCORE="0.75"

ccs -j ${THREADS} \
	--minLength ${MINLENGTH} \
	--maxLength ${MAXLENGTH} \
	--minPasses ${MINPASSES} \
	--minSnr ${MINSNR} \
	--minPredictedAccuracy ${MINPREDICTEDACCURACY} \
	--minReadScore ${MINREADSCORE} \
	--maxDropFraction 0.34 \
	--reportFile $sample.report.txt \
	$sample.subreads.bam $sample.fastq
	
